export const UPDATE_EMPLOYEES = 'UPDATE_EMPLOYEES';
export const UPDATE_EMPLOYEE_SKILLS = 'UPDATE_EMPLOYEE_SKILLS';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILLS = 'UPDATE_SKILLS';
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME';
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME';
export const UPDATE_FIELD = 'UPDATE_FIELD';